CONFIGS = {
    "LHNN_1DGaussianmixture" : {
        "seed" : 0,
        "load" : True,
        "path" : "/home/ycui/Documents/TSRLproject_JPMorgan/data/1DGaussianmixture.obj",
        "num_samples" : 20,
        "per_train" : 0.95,
        "input_dim" : 2,
        "dist_name" : '1D_Gauss_mix',
        "dt" : 0.05,
        "num_lf" : 400,
        "num_hidden": 100,
        "num_layers": 3,
        "output_dim": 2,
        "acti" : "sin",
        "baseline" : False,
        "field_type" : "solenoidal",
        "separate_fields" : False,
        "train_epoch" : 100,
        "train_step" : 1000,
        "path_model" : "/home/ycui/Documents/TSRLproject_JPMorgan/models/LHNN_1DGaussianmixture_sin.weights.h5",
    },
    "LHNN_3DRosenbrock" : {
        "seed" : 0,
        "load" : True,
        "path" : "/home/ycui/Documents/TSRLproject_JPMorgan/data/3DRosenbrock.obj",
        "num_samples" : 40, 
        "per_train" : 0.95, 
        "input_dim" : 6,
        "dist_name" : 'nD_Rosenbrock',
        "dt" : 0.025,
        "num_lf" : 1600,
        "num_hidden": 100,
        "num_layers": 3,
        "output_dim": 6, # Output dimension equals to the input dimension means it's LHNN.
        "acti" : "sin",
        "baseline" : False,
        "field_type" : "solenoidal",
        "separate_fields" : False,
        "train_epoch" : 100,
        "train_step" : 1000,
        "path_model" : "/home/ycui/Documents/TSRLproject_JPMorgan/models/LHNN_3DRosenbrock_sin.weights.h5",
    },
    "HNN_3DRosenbrock" : {
        "seed" : 0,
        "load" : True,
        "path" : "/home/ycui/Documents/TSRLproject_JPMorgan/data/3DRosenbrock.obj",
        "num_samples" : 40, 
        "per_train" : 0.95, 
        "input_dim" : 6,
        "dist_name" : 'nD_Rosenbrock',
        "dt" : 0.025,
        "num_lf" : 1600,
        "num_hidden": 100,
        "num_layers": 3,
        "output_dim": 2, # Output dimension equals to 2 means it's HNN.
        "acti" : "sin",
        "baseline" : False,
        "field_type" : "solenoidal",
        "separate_fields" : False,
        "train_epoch" : 100,
        "train_step" : 1000,
        "path_model" : "/home/ycui/Documents/TSRLproject_JPMorgan/models/HNN_3DRosenbrock_sin.weights.h5",
    },
    "LHNN_3DRosenbrock_T100" : {
        "seed" : 0,
        "load" : True,
        "path" : "/home/ycui/Documents/TSRLproject_JPMorgan/data/3DRosenbrock_T100.obj",
        "num_samples" : 40, 
        "per_train" : 0.95, 
        "input_dim" : 6,
        "dist_name" : 'nD_Rosenbrock',
        "dt" : 0.025,
        "num_lf" : 4000, # num_lf = T/dt
        "num_hidden": 100,
        "num_layers": 3,
        "output_dim": 6, # Output dimension equals to the input dimension means it's LHNN.
        "acti" : "sin",
        "baseline" : False,
        "field_type" : "solenoidal",
        "separate_fields" : False,
        "train_epoch" : 100,
        "train_step" : 1000,
        "path_model" : "/home/ycui/Documents/TSRLproject_JPMorgan/models/LHNN_3DRosenbrock_T100_sin.weights.h5",
    },
    "LHNN_3DRosenbrock_T150" : {
        "seed" : 0,
        "load" : True,
        "path" : "/home/ycui/Documents/TSRLproject_JPMorgan/data/3DRosenbrock_T150.obj",
        "num_samples" : 40, 
        "per_train" : 0.95, 
        "input_dim" : 6,
        "dist_name" : 'nD_Rosenbrock',
        "dt" : 0.025,
        "num_lf" : 6000, # num_lf = T/dt
        "num_hidden": 100,
        "num_layers": 3,
        "output_dim": 6, # Output dimension equals to the input dimension means it's LHNN.
        "acti" : "sin",
        "baseline" : False,
        "field_type" : "solenoidal",
        "separate_fields" : False,
        "train_epoch" : 100,
        "train_step" : 1000,
        "path_model" : "/home/ycui/Documents/TSRLproject_JPMorgan/models/LHNN_3DRosenbrock_T150_sin.weights.h5",
    },
    "LHNN_3DRosenbrock_T250" : {
        "seed" : 0,
        "load" : True,
        "path" : "/home/ycui/Documents/TSRLproject_JPMorgan/data/3DRosenbrock_T250.obj",
        "num_samples" : 40, 
        "per_train" : 0.95, 
        "input_dim" : 6,
        "dist_name" : 'nD_Rosenbrock',
        "dt" : 0.025,
        "num_lf" : 10000, # num_lf = T/dt
        "num_hidden": 100,
        "num_layers": 3,
        "output_dim": 6, # Output dimension equals to the input dimension means it's LHNN.
        "acti" : "sin",
        "baseline" : False,
        "field_type" : "solenoidal",
        "separate_fields" : False,
        "train_epoch" : 100,
        "train_step" : 1000,
        "path_model" : "/home/ycui/Documents/TSRLproject_JPMorgan/models/LHNN_3DRosenbrock_T250_sin.weights.h5",
    },
    "LHNN_2DNealsfunnel" : {
        "seed" : 0,
        "load" : True,
        "path" : "/home/ycui/Documents/TSRLproject_JPMorgan/data/2DNealsfunnel.obj",
        "num_samples" : 40, 
        "per_train" : 0.95, 
        "input_dim" : 4,
        "dist_name" : '2D_Nealsfunnel',
        "dt" : 0.025,
        "num_lf" : 10000,
        "num_hidden": 100,
        "num_layers": 3,
        "output_dim": 4, # Output dimension equals to the input dimension means it's LHNN.
        "acti" : "sin",
        "baseline" : False,
        "field_type" : "solenoidal",
        "separate_fields" : False,
        "train_epoch" : 100,
        "train_step" : 1000,
        "path_model" : "/home/ycui/Documents/TSRLproject_JPMorgan/models/LHNN_2DNealsfunnel_sin.weights.h5",
    },
    "LHNN_5DillconditionedGaussian" : {
        "seed" : 0,
        "load" : True,
        "path" : "/home/ycui/Documents/TSRLproject_JPMorgan/data/5DillconditionedGaussian.obj",
        "num_samples" : 40, 
        "per_train" : 0.95, 
        "input_dim" : 10,
        "dist_name" : '5D_illconditioned_Gaussian',
        "dt" : 0.025,
        "num_lf" : 10000,
        "num_hidden": 100,
        "num_layers": 3,
        "output_dim": 10, # Output dimension equals to the input dimension means it's LHNN.
        "acti" : "sin",
        "baseline" : False,
        "field_type" : "solenoidal",
        "separate_fields" : False,
        "train_epoch" : 100,
        "train_step" : 1000,
        "path_model" : "/home/ycui/Documents/TSRLproject_JPMorgan/models/LHNN_5DillconditionedGaussian_sin.weights.h5",
    },
    "LHNN_10DRosenbrock" : {
        "seed" : 0,
        "load" : True,
        "path" : "/home/ycui/Documents/TSRLproject_JPMorgan/data/10DRosenbrock.obj",
        "num_samples" : 40, 
        "per_train" : 0.95, 
        "input_dim" : 20,
        "dist_name" : 'nD_Rosenbrock',
        "dt" : 0.025,
        "num_lf" : 10000,
        "num_hidden": 100,
        "num_layers": 3,
        "output_dim": 20, 
        "acti" : "sin",
        "baseline" : False,
        "field_type" : "solenoidal",
        "separate_fields" : False,
        "train_epoch" : 100,
        "train_step" : 1000,
        "path_model" : "/home/ycui/Documents/TSRLproject_JPMorgan/models/LHNN_10DRosenbrock_sin.weights.h5",
    },
    "LHNN_AllenCahn" : {
        "seed" : 0,
        "load" : True,
        "path" : "/home/ycui/Documents/TSRLproject_JPMorgan/data/AllenCahn.obj",
        "num_samples" : 40, 
        "per_train" : 0.95, 
        "input_dim" : 50,
        "dist_name" : 'AllenCahn',
        "dt" : 0.025,
        "num_lf" : 10000, # it should be 250
        "num_hidden": 100,
        "num_layers": 3,
        "output_dim": 50, 
        "acti" : "sin",
        "baseline" : False,
        "field_type" : "solenoidal",
        "separate_fields" : False,
        "train_epoch" : 100,
        "train_step" : 1000,
        "path_model" : "/home/ycui/Documents/TSRLproject_JPMorgan/models/LHNN_AllenCahn_sin.weights.h5",
    },
    "LHNN_ellipticpde" : {
        "seed" : 0,
        "load" : True,
        "path" : "/home/ycui/Documents/TSRLproject_JPMorgan/data/ellipticpde.obj",
        "num_samples" : 40, 
        "per_train" : 0.95, 
        "input_dim" : 100,
        "dist_name" : 'ellipticpde',
        "dt" : 0.025,
        "num_lf" : 1600,
        "num_hidden": 100,
        "num_layers": 3,
        "output_dim": 100, 
        "acti" : "sin",
        "baseline" : False,
        "field_type" : "solenoidal",
        "separate_fields" : False,
        "train_epoch" : 100,
        "train_step" : 1000,
        "path_model" : "/home/ycui/Documents/TSRLproject_JPMorgan/models/LHNN_ellipticpde_sin.weights.h5",
    },
}